### ISSUE TITLE
Nieuw Groups aan maken in AWS Cognito 

### ISSUE THREAD

**Issue by Timo-Schuurman** [mostpros1/repository#110]
Ik ga in Cognito de nieuwe groups maken: HomeOwners en VakDeskundige. En ik verwijder de group Users

**Comment by Timo-Schuurman** [comment]
Nieuwe groups zijn aan gemaakt: HomeOwners en VakDeskundige, later maak ik nog rolls in deze groups wanneer ik het nodig ben, als iemand extra rolls nodig heeft voor deze groups maak dan gerust je zelf aan

**Comment by Timmhart** [comment]
Kan je ipv VakDeskundige > HomeSpecialist van maken? Zo blijft het consistent in het engels.
@Timo-Schuurman

**Comment by Timo-Schuurman** [comment]
VakDeskundige verwijdert, HomeSpecialist toegevoegd

**Comment by Timo-Schuurman** [comment]
HomeProfessionals bij toe voegen
