### ISSUE TITLE
Task/specialists result page components and functionality

### ISSUE THREAD

**Issue by Robinzhao69** [mostpros1/repository#128]
Hier komen de nieuwe updates voor de klussen/vakspecialisten pagina.

**Comment by Robinzhao69** [comment]
![image](https://github.com/mostpros1/repository/assets/70864835/95212970-38af-4959-ad1d-1cb918c6af25)
Ik heb een filterbar component aangemaakt voor de resultaten pagina van de specialisten/huiseigenaren.
Deze is alleen nog niet functioneel.

**Comment by Timmhart** [comment]
@Robinzhao69 Klopt het dat hier de filterbar nog moet?
