### ISSUE TITLE
Offertestraat stap 3

### ISSUE THREAD

**Issue by Timmhart** [mostpros1/repository#13]
<img width="1439" alt="Scherm­afbeelding 2023-11-13 om 09 42 17" src="https://github.com/mostpros1/repository/assets/63649558/4e2e84a2-f56b-4db2-8265-5c8a7834cda8">

Bij stap 3 in de offertestraat van de huiseigenaren is er een invulveld waar aanvullende informatie ingevuld kan worden. In de beschrijving staat vermeld dat het niet verplicht is, maar je kan het veld niet leeg meesturen.

**Comment by Robinzhao69** [comment]
ik heb bij de textarea de required attribute weggehaald, dus nu kan je weer naar de volgende stap zonder iets in te vullen
