### ISSUE TITLE
Optimization offerteStraat

### ISSUE THREAD

**Issue by Timo-Schuurman** [mostpros1/repository#133]
Optimization offerteStraat

feedback en verificatie op inputfields (error state bijvoorbeeld)

<img width="1381" alt="Scherm­afbeelding 2023-12-11 om 15 54 36" src="https://github.com/mostpros1/repository/assets/63649558/42db291f-82ba-416c-8492-d2257ba18bea">
Ervoor zorgen dat je alleen postcode en alleen plaatsen in vult. Handig om hierbij onderzoek te doen naar best practices.

 ----- 
<img width="451" alt="Scherm­afbeelding 2023-12-11 om 16 06 05" src="https://github.com/mostpros1/repository/assets/63649558/d96480a3-e15d-4783-8b41-2e76155db81d">

Deze input field opsplitsen in 1 kleine en 1 grote input field. 

Voorbeeld:

![image](https://github.com/mostpros1/repository/assets/63649558/a2aa3ab8-504f-46d9-a020-f3f56017e385)
 

----- 
<img width="1400" alt="Scherm­afbeelding 2023-12-11 om 16 07 14" src="https://github.com/mostpros1/repository/assets/63649558/6188e02f-7054-440d-b593-cdcc8427d20b">
Labels koppelen aan input fields zie: 
https://www.anysurfer.be/nl/documentatie/artikels/detail/verbind-labels-met-formuliervelden

**Comment by Robinzhao69** [comment]
![image](https://github.com/mostpros1/repository/assets/70864835/c41ea6a3-c802-4558-8206-0c11b0913066)
De input voor de telefoonnummer heb ik er in kunnen krijgen, maar probleem nu is dat ik de input van de form terug mee moet geven aan de registerdata. Alleen ik krijg deze error van type script. Het lijk op een type error dus ik moet even kijken wat er precies fout gaat.

**Comment by Robinzhao69** [comment]
![image](https://github.com/mostpros1/repository/assets/70864835/f638b9dd-b1d7-46b2-ad85-daf69dd1e260)
Het probleem is gefixt door een condition toe te voegen, waarbij de value eerst een lege string is en daarna de value van de input.

**Comment by Robinzhao69** [comment]
![image](https://github.com/mostpros1/repository/assets/70864835/4e3f3a03-5179-4077-81f2-df3d1324127c)
De loginform heeft nu error messages als de user niks heeft ingevuld.
