### ISSUE TITLE
Navbar optimalisation

### ISSUE THREAD

**Issue by Timmhart** [mostpros1/repository#135]
Small optimalisation for the navbar:

- [x] Change "inloggen" > image below

<img width="113" alt="Scherm­afbeelding 2023-12-11 om 15 47 11" src="https://github.com/mostpros1/repository/assets/63649558/b088ed24-3fa2-4f39-9ed0-3b51596a022e">

- [x] Change "Inschrijven als vakspecialist" > image below

<img width="223" alt="Scherm­afbeelding 2023-12-11 om 15 47 44" src="https://github.com/mostpros1/repository/assets/63649558/b975e4c4-72b1-46b7-9308-d0f5c392df68">

- [x] Klussen dropdown > Image below

<img width="1440" alt="Scherm­afbeelding 2023-12-12 om 10 30 45" src="https://github.com/mostpros1/repository/assets/63649558/13725f1d-980d-4666-9a7c-088f16f91b24">

**Comment by Robinzhao69** [comment]
![image](https://github.com/mostpros1/repository/assets/70864835/1ca2b76a-47d1-415a-864d-6c1c4cde5478)
Ik heb de buttons en icon veranderd zoals het hier staat.

**Comment by Robinzhao69** [comment]
![image](https://github.com/mostpros1/repository/assets/70864835/1952edf9-4dac-4613-8448-0da759fab297)
er is een nieuwe nav link toegevoegd met een dropdown menu. De links in de dropdown leiden nog nergens naartoe.
