### ISSUE TITLE
Home page uitlijning

### ISSUE THREAD

**Issue by Timmhart** [mostpros1/repository#14]
<img width="1439" alt="Scherm­afbeelding 2023-11-13 om 11 12 37" src="https://github.com/mostpros1/repository/assets/63649558/5b07dbcd-5cd2-4f27-a0ca-8f3d4cfe2353">
<img width="1439" alt="Scherm­afbeelding 2023-11-13 om 11 13 07" src="https://github.com/mostpros1/repository/assets/63649558/28e2611a-95e5-453c-b07d-dcc8307d9c5b">
<img width="1439" alt="Scherm­afbeelding 2023-11-13 om 11 13 11" src="https://github.com/mostpros1/repository/assets/63649558/205e9e83-03a9-41ed-b26b-6f40aeef2649">
<img width="1439" alt="Scherm­afbeelding 2023-11-13 om 11 14 04" src="https://github.com/mostpros1/repository/assets/63649558/bd1068e1-6530-45fb-8229-f0439ce543c5">

Kijk hier goed naar het design voor de uitlijning

**Comment by HisjaamB** [comment]
Ik vind de uitlijning verder helemaal prima. Kleine opmerking over de "Waarom Mostpros". Die vind ik een beetje vreem overkomen qua design. Misschien het lettertype van de cijfers in combinatie met de lange zin erachter... 

De nav bar mag wel een full widht uitlijning hebben vind ik. Of een aanzienlijk bredere nav bar dan dat hij nu is. Dit samen laten lopen met de footer lijkt me handig. Zodat ehader en footer dezelfde uitlijning hebben en content zijn eigen uitlijning.

Maar verder goed, laten zo voor de 1e versie denk ik

**Comment by Robinzhao69** [comment]
@HisjaamB is het dan een idee dat ik de nav weer op de oude breedte hou 1500px? En over de footer is het meer van dat er niet veel content in zit en dat daardoor de tussenruimtes misschien te groot worden. Misschien dat ik dan de lettertype van de footer met 2 px kan vergroten?

**Comment by Robinzhao69** [comment]
![image](https://github.com/mostpros1/repository/assets/70864835/650234c4-9036-40da-90b8-39b317c5e151)
![image](https://github.com/mostpros1/repository/assets/70864835/89a75887-ca43-44cc-9a35-63a13f3df41e)
Ik heb de maximale breedte van de nav en footer veranderd. Voor de nav is het van 1000px -> 1200px en de footer 700px -> 1000px. @Timmhart @HisjaamB
