### ISSUE TITLE
Navigation 'Hoe werkt het?'

### ISSUE THREAD

**Issue by Timmhart** [mostpros1/repository#15]
<img width="1439" alt="Scherm­afbeelding 2023-11-13 om 11 11 27" src="https://github.com/mostpros1/repository/assets/63649558/20cfbec7-b1aa-4810-8335-2cc4da86fe96">

Hoe werkt het? --> Hoe het werkt

**Comment by Robinzhao69** [comment]
Ik heb het vraagteken weggehaald
