### ISSUE TITLE
Optimalisaties Home

### ISSUE THREAD

**Issue by Timmhart** [mostpros1/repository#158]
<img width="1439" alt="Scherm­afbeelding 2023-12-18 om 14 28 55" src="https://github.com/mostpros1/repository/assets/63649558/3ff0064d-8e2b-4bbc-94ee-fbe6cc17ca56">

- [x] Font size kleiner
- [x] "inschrijven als vakspecialist" geen background, alleen border

<img width="1108" alt="Scherm­afbeelding 2023-12-18 om 14 31 20" src="https://github.com/mostpros1/repository/assets/63649558/328a6fc4-d2dc-452b-ae38-eab7dab283ef">

- [x] Input veld mag minder breed en iets naar beneden
- [x] Inschrijven als vakspecialist mag hier weg

<img width="1440" alt="Scherm­afbeelding 2023-12-18 om 14 35 14" src="https://github.com/mostpros1/repository/assets/63649558/e407a517-f910-4dd0-a0ca-eff9cc26cb6c">

- [x] Waarom mostpros > Waarom kiezen voor Mostpros?

<img width="1440" alt="Scherm­afbeelding 2023-12-18 om 14 35 58" src="https://github.com/mostpros1/repository/assets/63649558/ee744d9b-4609-455b-a23a-6e3c10e7d96c">

- [x] Reviews > Echte ervaringen, echte mensen

**Comment by Robinzhao69** [comment]
![image](https://github.com/mostpros1/repository/assets/70864835/47ecb382-59a2-4b99-8279-c2372f2022c3)

Ik heb bij de navbar de achtergrond van de button weggehaald voor een border. Verder heb ik nog wat teksten veranderd en de reviews willekeurig van het internet gehaald.

**Comment by Robinzhao69** [comment]
![image](https://github.com/mostpros1/repository/assets/70864835/e85dfa29-5bd6-4aac-95b4-b2342ac1fb57)
![image](https://github.com/mostpros1/repository/assets/70864835/10b76d3f-e976-4def-8309-a676c4823a3c)
