### ISSUE TITLE
Placeholders invulvelden

### ISSUE THREAD

**Issue by Timmhart** [mostpros1/repository#17]
<img width="1439" alt="Scherm­afbeelding 2023-11-13 om 11 23 44" src="https://github.com/mostpros1/repository/assets/63649558/c299ae8e-a4ca-4a6c-ada1-3b5ad3f74d74">

Labels en placeholders hebben nu dezelfde benamingen, lijkt me een beetje dubbel op. 
Ik zou de placeholders aanpassen naar bijvoorbeeld:
Email > example@example.com of naam@domein.nl
Postcode > 1234AB
Stad > Amsterdam of Plaatsnaam

**Comment by Robinzhao69** [comment]
Ik heb de placeholders in de form aangepast naar dit -> Email > [example@example.com](mailto:example@example.com) of [naam@domein.nl](mailto:naam@domein.nl)
Postcode > 1234AB
Stad > Amsterdam of Plaatsnaam
