### ISSUE TITLE
user registreren gooit geen foutmelding op een formulier

### ISSUE THREAD

**Issue by roberthopman** [mostpros1/repository#231]
Zie laatste developer console foutmelding rondom phone number format:

<img width="521" alt="Screenshot 2024-01-26 at 11 23 32" src="https://github.com/mostpros1/repository/assets/3865531/acd39b15-f4fa-46b6-b043-37b79df36660">

**Comment by roberthopman** [comment]
### voor meest ongebruiksvriendelijke eerste verbetering:

<img width="799" alt="Screenshot 2024-01-26 at 11 52 28" src="https://github.com/mostpros1/repository/assets/3865531/67edaf6d-4caf-442a-9f90-b481aa288bd5">

**Comment by Robinzhao69** [comment]
![image](https://github.com/mostpros1/repository/assets/70864835/57e57b46-c4d2-41bf-a548-e13ceece64
Zowel de login als register form krijgen nu een error message boven de form weergeven. Deze error messages komen van amplify zelf.
