### ISSUE TITLE
Testing error: custom functions

### ISSUE THREAD

**Issue by Tarik-Bag** [mostpros1/repository#240]
Expected situation: I want to add custom functions to the commands.ts file to use them as global functions in all other testing files.

Actual situation: There are errors occuring and functions doesnt work on another file. 
For example, functions are not available on LisaTest-Stap1.cy.js file (file location: web/cypress/e2e/LisaTest/LisaTest-Stap1.cy.js).

I have been using the 'tarik-testing' branch, and the file with problem is located at web/cypress/support/commands.ts. 
If you navigate to the file, you will see errors at the beginning of each function (line 40, 44, and 52).

![Screenshot 2024-01-31 142122](https://github.com/mostpros1/repository/assets/103409369/1132280e-8375-4ef5-93fc-9b5f6c08a656)

What I did: I changed the extensions of commands file, because I thought I had to use .js file instead of .ts file. But this didnt help. There were no errors anymore, but functions didnt work again.

My researchs: I made a research on cypress docs, but I couldnt find any solution. This is the documentation: https://docs.cypress.io/api/cypress-api/custom-commands

And I researched at StackOverflow aswell, but I still couldnt find a solution.

I need some help about this problem.

**Comment by roberthopman** [comment]
Good start, could you:
1. push the branch to the repo if not already done and updated
2. add a link, or multiple links, to the relevant line of code, it should directly link to the relevant line of code (research this)
3. share the steps how you think it should work (e.g. create a new file, write a command, import the file, then it should be used as follows...)
4. please describe in detail: "There are errors occuring". If we do not know these errors, we can not solve them. 
5. Details matter.

**Comment by roberthopman** [comment]
Succes!

<img width="502" alt="Screenshot 2024-01-31 at 16 50 27" src="https://github.com/mostpros1/repository/assets/3865531/a9e3ef4b-d5d7-44bf-8373-ac927b3c276d">
