### ISSUE TITLE
Huiseigenaren offertestraat email

### ISSUE THREAD

**Issue by Timmhart** [mostpros1/repository#25]
Gebruiker re-directen naar juiste pagina op basis van email-herkenning. 
Nu vul je bij stap 4 een emailadres in:
Herkent het systeem het emailadres > ga dan naar log in
Herkent het systeem het emailadres niet > ga dan naar sign up

**Comment by JelaniAlexis** [comment]
https://github.com/mostpros1/repository/commit/4e8e5814e23df908aa3ab7b2726517b1d1f34fea
