### ISSUE TITLE
Lambda Network Error

### ISSUE THREAD

**Issue by Bekoo023** [mostpros1/repository#296]
Wanneer ik een lampda functie wil maken krijg ik deze error.

![Lampda](https://github.com/mostpros1/repository/assets/124692936/b6dca677-69e1-40c0-93fe-f3a1a8991d91)

**Comment by TimHei123** [comment]
heb ik ook

**Comment by roberthopman** [comment]
AWS ticket: https://support.console.aws.amazon.com/support/home?region=eu-north-1#/case/?displayId=171015703301781&language=en

**Comment by roberthopman** [comment]
14:45 - 15:00 call met Abdel, Bekir, Matthew en Robert over waar het vast loopt. Resultaat: AWS tickets worden niet nauwkeurig bijgehouden.

**Comment by Bekoo023** [comment]
Bericht verstuurd naar support. Afwachting op antwoord
