### ISSUE TITLE
professional aanmeld form

### ISSUE THREAD

**Issue by TimHei123** [mostpros1/repository#321]
![image](https://github.com/mostpros1/repository/assets/58216216/2d7be802-ad1c-4f0f-baf3-f3659c156b75)
het formulier zegt dat mobile nummer niet het juiste formaat heeft. dit terwijl ik op 2 nummers neer die ik ergens veranderd heb mijn eigen nummer gebruik.

**Comment by Jass201** [comment]
Wat geeft ie aan als je +31 gebruikt?

**Comment by TimHei123** [comment]
is onmogelijk. je hebt niet genoeg ruimte. maar ik kan ook de form van home owner gebruiken

**Comment by Jass201** [comment]
![Screenshot 2024-03-12 152950](https://github.com/mostpros1/repository/assets/118255221/08b98298-7cc4-415c-a23f-4c81af2e8567)

Bij mij heb je dat probleem niet. Dit is bij de ( Inschrijven als vakspecialist ) tabje. Kan het zijn dat je een oude code hebt?

**Comment by Jass201** [comment]
![Screenshot 2024-03-12 153211](https://github.com/mostpros1/repository/assets/118255221/7d343fa0-8eaf-4835-b835-27914a22348c)
-> Dit is na de verstuur knopje

**Comment by TimHei123** [comment]
de bevestigings pagina heb ik wel alleen hoeozo zou je een nederlandse vlag hebben en alsnog +31 moeten zetten. dan moet ik proberen de beperking te veranderen
