### ISSUE TITLE
AWS Build Error

### ISSUE THREAD

**Issue by Bekoo023** [mostpros1/repository#347]
![Screenshot 2024-03-20 171742](https://github.com/mostpros1/repository/assets/124692936/27cae14b-25cc-4445-91e2-59d501a81d51)

Tijdens het builden van main naar de de website ontstaat er deze error

**Comment by TimHei123** [comment]
als ik de backend wil pullen krijg ik dit:
![image](https://github.com/mostpros1/repository/assets/58216216/33892485-eb64-4de6-9c17-d2faf26daf25)

**Comment by Bekoo023** [comment]
Bij: Choose your default editor: none. moet je VS code aankruisen misschien ligt het daaraan

**Comment by TimHei123** [comment]
het werkte de hele tijd als ik none zei. erger nog in de wiki staat ook none omdat het zo altijd werkte

**Comment by TimHei123** [comment]
ik heb amplify map verwijderd en dan werkte het

**Comment by TimHei123** [comment]
maar op web weet ik het niet

**Comment by TimHei123** [comment]
een update can ik ook niet uitvoeren
![image](https://github.com/mostpros1/repository/assets/58216216/44c4fc1e-9e03-4b24-a486-eecb2360b7d5)

**Comment by roberthopman** [comment]
@TimHei123 schrijf het uit, met relevante links naar onderdelen en bronnen: https://github.com/mostpros1/repository/wiki/debugging

Zodat iedereen dit binnen 5 minuten kan begrijpen. inzien en reproduceren op een verse `git clone`.

**Comment by TimHei123** [comment]
![image](https://github.com/mostpros1/repository/assets/58216216/0ac1ff0a-a483-4adb-9fa5-d7664dfce0c0)
![image](https://github.com/mostpros1/repository/assets/58216216/19a76d1b-24a2-49a6-867b-5b01c95b39a1)
![image](https://github.com/mostpros1/repository/assets/58216216/291785df-303f-402a-b2e1-a4bd84409543)



welke stappen heb ik gedaan om een oplossing te zoeken?

1. amplify verwijderen en opnieuw pullen
2. dan probeerde ik auth te updaten locaal op mijn laptop
3. als laatst probeerde ik te pushen, maar kreeg dezelfde error als wat we kregen bij de amplify web build

weet iemand wat ik nog kan doen want het is een aws probleem?

**Comment by roberthopman** [comment]
Eerst vragen aan @MatthewWillems

**Comment by Bekoo023** [comment]
![Screenshot 2024-04-03 113234](https://github.com/mostpros1/repository/assets/124692936/08d9bdf0-bdd4-47b0-b45a-454433cc8d15)
![Screenshot 2024-04-03 113501](https://github.com/mostpros1/repository/assets/124692936/f883249a-63a1-435c-a141-74f27698be9f)

Op AWS kan hij de aws-sdk bestand niet vinden. In mijn Visual Studio Code geeft hij geen error aan.

**Comment by roberthopman** [comment]
@Bekoo023 Wil je ondersteuning in een call? Zo ja, alsjeblieft uitschrijven hoe ik lokaal en op AWS kan reproduceren.

**Comment by Bekoo023** [comment]
@roberthopman Zodra je inlogd bij mostpros in AWS, moet je naar aws amplify gaan. Dan druk je op mostpros en dan bij hosting environment klik je op de rode kruis bij acceptance. Hierbij kom je in een scherm waar je de error code kan vinden en ook hem opnieuw kan redeployen.
