### ISSUE TITLE
Hoe werkt het - Page

### ISSUE THREAD

**Issue by Timmhart** [mostpros1/repository#87]
Hoe werkt het pagina de drie stappen van de home pagina pakken.

<img width="776" alt="Scherm­afbeelding 2023-11-21 om 17 03 57" src="https://github.com/mostpros1/repository/assets/63649558/f6e838a9-c42b-4cf9-85f2-7988c6b35c3f">

**Comment by Robinzhao69** [comment]
Ik heb de aanpassingen doorgevoerd. Alleen zijn de img misschien een beetje te klein? Tim zou jij misschien die images kunnen croppen en minder white space geven?
![steps-example](https://github.com/mostpros1/repository/assets/70864835/e03c61ab-884b-461c-8419-ecd220ad8991)

**Comment by Timmhart** [comment]
Kan je dit ook verwerken op https://main.d2j290dx5bs7ht.amplifyapp.com/hoe-werkt-het
De visual van nu mag eraf.

**Comment by Timmhart** [comment]
@Robinzhao69  ^^

**Comment by Robinzhao69** [comment]
Ik heb de image weggehaald en verwisseld met de MostprosDesc component. 
![image](https://github.com/mostpros1/repository/assets/70864835/8b06bcc7-23ee-48f7-88e1-e34ba3792819)
