### ISSUE TITLE
Problemen met react-router integreren in react-native inplaats van expo-router

### ISSUE THREAD

**Issue by MaxBouricius** [mostpros1/repository#96]
Oprecht alles wat ik probeer krijg ik een van 2 errors:

1. Unmatched route
2. Can't find "main" in kort zecht hij hier dat het mischien niet goed gebuild is, maar ik weet zeker dat hij dat wel is.

**Comment by Timmhart** [comment]
@MaxBouricius Deze issue kan geclosed worden toch?
